# Generated by Django 3.0.3 on 2020-06-30 08:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Возраст')),
                ('description', models.TextField(verbose_name='Информация')),
                ('image', models.ImageField(upload_to='guides/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Гид и менеджер',
                'verbose_name_plural': 'Гиды и менеджеры',
            },
        ),
        migrations.CreateModel(
            name='Hike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название похода')),
                ('tagline', models.TextField(default='', verbose_name='Слоган')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='hikes/', verbose_name='Фотография')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('region', models.CharField(max_length=50, verbose_name='Регион')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Начало похода')),
                ('finish_date', models.DateField(default=datetime.date.today, verbose_name='Окончание похода')),
                ('duration', models.PositiveIntegerField(default=0, help_text='in days', verbose_name='Продолжительность')),
                ('price', models.PositiveIntegerField(default=0, help_text='Цена в грн', verbose_name='Стоимость')),
                ('url', models.SlugField(max_length=130, unique=True)),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chogori.Category', verbose_name='Категория')),
                ('guide', models.ManyToManyField(related_name='hike_guide', to='chogori.Guide', verbose_name='Гид')),
                ('manager', models.ManyToManyField(related_name='hike_manager', to='chogori.Guide', verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Поход',
                'verbose_name_plural': 'Походы',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('text', models.TextField(max_length=5000, verbose_name='Отзыв')),
                ('hike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chogori.Hike', verbose_name='поход')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chogori.Reviews', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='HikePhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='hike_photos/', verbose_name='Фотография')),
                ('hike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chogori.Hike', verbose_name='Поход')),
            ],
            options={
                'verbose_name': 'Фотография с похода',
                'verbose_name_plural': 'Фотографии с похода',
            },
        ),
    ]
